// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTeacher(ctx context.Context, email string) (sql.Result, error)
	DeleteTeacher(ctx context.Context, id int64) error
	GetTeacher(ctx context.Context, id int64) (Teacher, error)
	ListTeachers(ctx context.Context) ([]Teacher, error)
}

var _ Querier = (*Queries)(nil)
